### ISSUE TITLE
When Better Chat plugin is installed, the names are doubled

### ISSUE THREAD

**Issue by Bazimek** [alexander171294/RustMon#23]
![image](https://user-images.githubusercontent.com/17622398/147388911-e2aaab67-6e59-42f8-a43d-d55350d18499.png)

**Comment by Bazimek** [comment]
If you can make it (when better chat is installed) like this [TITLE] [NAME]: [MESSAGE] that will be really nice.

**Comment by alexander171294** [comment]
this plugin? https://umod.org/plugins/better-chat

**Comment by Bazimek** [comment]
Yes.

**Comment by alexander171294** [comment]
Done, can you test it, and say me if works or not?

thanks.

**Comment by Bazimek** [comment]
Sure I can.

**Comment by Bazimek** [comment]
Oh my god! You did so many great stuff in this update! This is like very big update. Looks so .... good! The best Rust Rcon tool ever. I love that I can see the server message in chat now, I just LOVE the console update (font and spacing if you using banlist or status command)

The yellow and VAC icons are very nice function too. The right click on names with so many options is awesome!

New favicon is a nice detail too!

Unfortunatelly I have still double names in chat.

**Comment by alexander171294** [comment]
Thanks, I test it local with betterChat plugin and i can see ok the nick with better chat plugin format as this picture:

![image](https://user-images.githubusercontent.com/2080955/150209292-f9e23856-6edd-48b2-8ee1-a49adbdf10b1.png)

but i think, exist a bug when the dashboard is open, also i think my endpoint isn't updated.

**Comment by Bazimek** [comment]
yes but look at the chat it is [name] [title] [name] [text]

Can it be with this plugin [title] [name] [text] like in th econsole?

**Comment by alexander171294** [comment]
like the last message

**Comment by Bazimek** [comment]
Exactly.

**Comment by alexander171294** [comment]
i think is because are not really updated, in my instance is the same, i can't see correctly, but when i run it locally it works, is strange.

**Comment by Bazimek** [comment]
And can I somehow fix that for me?

**Comment by alexander171294** [comment]
can you pull and try again?

**Comment by Bazimek** [comment]
Seems to like if they got the title is correct, but without it it is not:

![image](https://user-images.githubusercontent.com/17622398/150361898-5fdfcdbb-4193-4f28-89bb-68808949dad3.png)

**Comment by alexander171294** [comment]
try again plz

**Comment by Bazimek** [comment]
Looking goood!

**Comment by Bazimek** [comment]
Oh it works only when I start up and the history names was OK. But a new messages are not okay :(

**Comment by alexander171294** [comment]
I pushed new update, check it, and tell me if its work

**Comment by Bazimek** [comment]
I think it is working ... nice job!

**Comment by Bazimek** [comment]
I move it to the website FTP like previous version, but I cannot again connect because of that https stuff if you remember. And I allow the settings in your tutorial but it does not work for this version.

**Comment by alexander171294** [comment]
hmmm, were you able to fix it?, i don't remember your webpage to see what is the problem :(

**Comment by Bazimek** [comment]
IT was working on previous version IT Is rcon.gamearea.cz without https on different hosting IT works but not in https even with your tutorial

**Comment by Bazimek** [comment]
And some more bugs to report. In one player nickname (what I see for now)
![image](https://user-images.githubusercontent.com/17622398/150579989-9289c7d7-1ec6-43bc-a598-88b34790dd7a.png)
It is not working I think it is because he has ":)" in his nickname.

And second thing:
When I want to use copy steamID it says clipboard is disabled? (I am using http on different host for testing because as you know it is not working for me on that my main website)

**Comment by alexander171294** [comment]
Related to the first bug:
yes it's because the message without profile use : to split and in that case can't match the regex, it's really difficult to support that plugin because have a strange format in rcon console.

The second thing, I discovered that the clipboard only works in specific condition (a limitation of browser), the clipboard only works with ssl, localhost, but have a lot of problems, so I added the steam id in variety of places, like if you click (left click) in chat message you will see a popup with the steam id for copy, and that also works in player list.

now i pushed new feature, when a user report to another user with F7, then a popup is showed in top-right corner.

in the future i will add a popup with list of reports.

**Comment by Bazimek** [comment]
But the clipboard was working for me in previous version. And I get that it is not easy to fully integrate the plugin but I think thats ok. It is for me only for this one player with ":)" in nickname. But it works really great. Just IDK why now it does not work in my main domain with https (but disabled for this subdomain) like previous version was working.

**Comment by alexander171294** [comment]
First: I updated the script adding multiple connection history (storing in a list the different connections, called previous sessions).

Second: your ssl is broken in https://rcon.gamearea.cz/ i got a warning of "unsecured site", could be that the problem of clipboard.

**Comment by Bazimek** [comment]
I tried different webhost without SSL and the clipboard still does not work.

**Comment by alexander171294** [comment]
Try with last updated (v1.3.0), and tell me what happens.

I implemented an old clipboard copy method, previous to 2015 but i think, that method has more support.

**Comment by Bazimek** [comment]
Ye now the clipboard is working.
